---
- hosts: localhost
  connection: local

  vars:
    k8s_config_file: /Users/ruchira/.kube/config
    k8s_dashboard_host_name: k8s.server.ruchij.com

  tasks:
#    - name: Deploy Elasticsearch
#      block:
#        - name: Add helm elastic repository
#          command: helm repo add elastic https://helm.elastic.co
#
#        - name: Deploy Elasticsearch helm chart
#          shell: |
#            KUBECONFIG={{ k8s_config_file }} helm install elasticsearch elastic/elasticsearch \
#              --set extraEnvs=[{ name: "discovery.type", value: "single-node" }] \
#              --set imageTag=7.17.5 \
#              --set replicas=1 \
#              --namespace logging \
#              --create-namespace
#
#    - name: Generate Route 53 credentials
#      terraform:
#        project_path: ./route-53-credentials
#        force_init: yes

    - name: Create output directories
      block:
        - file:
            path: output
            state: directory
        - file:
            path: output/cluster-issuer
            state: directory
        - file:
            path: output/dashboard
            state: directory

    - name: Setup Cert Manager in K8s
      block:
        - name: Install Cert Manager
          command: |
            kubectl apply \
              -f https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml \
              --kubeconfig {{ k8s_config_file }}

        - name: Delete Cert Manager web hooks
          block:
            - name: Delete mutating webhook
              command: |
                kubectl delete \
                  mutatingwebhookconfiguration.admissionregistration.k8s.io cert-manager-webhook \
                  --kubeconfig {{ k8s_config_file }}

            - name: Delete validating webhook
              command: |
                kubectl delete \
                   validatingwebhookconfigurations.admissionregistration.k8s.io cert-manager-webhook \
                   --kubeconfig {{ k8s_config_file }}

        - name: Render K8s resource files
          template:
            src: "{{ item }}"
            dest: output/cluster-issuer/{{ item | basename }}
          with_fileglob:
            - k8s-resource-files/cluster-issuer/*.yaml
          vars:
            aws_access_key_id: "{{ lookup('aws_ssm', '/k8s/cert-manager/access-key-id', region='ap-southeast-2') }}"
            aws_secret_access_key: "{{ lookup('aws_ssm', '/k8s/cert-manager/secret-access-key', region='ap-southeast-2') }}"

        - name: Apply K8s resource files
          command: kubectl apply -f output/cluster-issuer --kubeconfig {{ k8s_config_file }}

    - name: Install K8s dashboard
      block:
        - name: Add helm K8s dashboard repository
          command: helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/

        - name: Deploy K8s dashboard
          shell: |
            KUBECONFIG={{ k8s_config_file }} helm install dashboard-deploy kubernetes-dashboard/kubernetes-dashboard \
              --set protocolHttp=true \
              --set service.externalPort=80 \
              --set extraArgs="{--enable-insecure-login=true}" \
              --namespace kubernetes-dashboard \
              --create-namespace

        - name: Render K8s resource files
          template:
            src: "{{ item }}"
            dest: output/dashboard/{{ item | basename }}
          with_fileglob:
            - k8s-resource-files/dashboard/*.yaml

        - name: Apply K8s resource files
          command: kubectl apply -f output/dashboard --kubeconfig {{ k8s_config_file }}