apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt-prod
spec:
  acme:
    email: me@ruchij.com
    server: https://acme-v02.api.letsencrypt.org/directory

    privateKeySecretRef:
      name: lets-encrypt-private-key

    solvers:
      - dns01:
          route53:
            region: ap-southeast-2
            accessKeyID: {{ aws_access_key_id }}
            secretAccessKeySecretRef:
              name: cert
              key: AWS_SECRET_ACCESS_KEY