apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin-deployment
  namespace: jellyfin
spec:
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - name: jellyfin-container
          image: jellyfin/jellyfin:10.10.7
          readinessProbe:
            httpGet:
              port: jellyfin-port
              path: /web
          livenessProbe:
            httpGet:
              port: jellyfin-port
              path: /web
          startupProbe:
            periodSeconds: 15
            initialDelaySeconds: 60
            failureThreshold: 10
            httpGet:
              port: jellyfin-port
              path: /web
          ports:
            - name: jellyfin-port
              containerPort: 8096
          volumeMounts:
            - mountPath: /data/movies
              name: movies-folder
            - mountPath: /data/movies-1
              name: movies-folder-1
            - mountPath: /data/tv-shows
              name: tv-shows-folder
            - mountPath: /data/tv-shows-1
              name: tv-shows-folder-1
            - mountPath: /config
              name: jellyfin-config
      volumes:
        - name: movies-folder
          hostPath:
            path: /media/plex/movies
            type: Directory
        - name: movies-folder-1
          hostPath:
            path: /media/disk/media/movies
            type: Directory
        - name: tv-shows-folder
          hostPath:
            path: /media/plex/tv-shows
            type: Directory
        - name: tv-shows-folder-1
          hostPath:
            path: /media/disk/media/tv-shows
            type: Directory
        - name: jellyfin-config
          hostPath:
            path: /home/ruchira/Data/jellyfin
            type: Directory
