apiVersion: v1
kind: ConfigMap
metadata:
  name: redpanda-console-config
  namespace: kafka
data:
  config.yaml: |
    kafka:
      brokers:
        - kafka-broker-0.kafka-headless.kafka.svc.cluster.local:9092
      schemaRegistry:
        enabled: true
        urls:
          - http://schema-registry:8081
