apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex-certificate
  namespace: plex
spec:
  secretName: plex-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
  dnsNames:
    - plex.home.ruchij.com