apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-deployment
  namespace: plex
spec:
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - name: plex-container
          image: plexinc/pms-docker:1.42.1.10060-4e8b05daf
          readinessProbe:
            httpGet:
              port: plex-port
              path: /web
          livenessProbe:
            httpGet:
              port: plex-port
              path: /web
          startupProbe:
            periodSeconds: 5
            failureThreshold: 10
            httpGet:
              port: plex-port
              path: /web
          ports:
            - name: plex-port
              containerPort: 32400
          volumeMounts:
            - mountPath: /data/movies
              name: movies-folder
            - mountPath: /data/movies-1
              name: movies-folder-1
            - mountPath: /data/tv-shows
              name: tv-shows-folder
            - mountPath: /data/tv-shows-1
              name: tv-shows-folder-1
            - mountPath: /config
              name: plex-config
      volumes:
        - name: movies-folder
          hostPath:
            path: /media/plex/movies
            type: Directory
        - name: movies-folder-1
          hostPath:
            path: /media/disk/media/movies
            type: Directory
        - name: tv-shows-folder
          hostPath:
            path: /media/plex/tv-shows
            type: Directory
        - name: tv-shows-folder-1
          hostPath:
            path: /media/disk/media/tv-shows
            type: Directory
        - name: plex-config
          hostPath:
            path: /home/ruchira/Data/plex
            type: Directory
