apiVersion: v1
kind: Service
metadata:
  name: plex-service
  namespace: plex
spec:
  selector:
    app: plex
  type: NodePort
  ports:
    - name: plex-port
      port: 32400
      targetPort: plex-port
      nodePort: 32400