services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.2
    restart: unless-stopped
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka-broker:
    image: confluentinc/cp-kafka:7.9.2
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://server.internal.ruchij.com:9092

  schema-registry:
    image: confluentinc/cp-schema-registry:7.9.2
    restart: unless-stopped
    depends_on:
      - kafka-broker
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: server.internal.ruchij.com:9092

  kpow:
    image: factorhouse/kpow-ce:94.2
    restart: unless-stopped
    mem_limit: 4g
    ports:
      - 3000:3000
    depends_on:
      - kafka-broker
      - schema-registry
    environment:
      BOOTSTRAP: server.internal.ruchij.com:9092
      SCHEMA_REGISTRY_URL: http://schema-registry:8081
