version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    restart: unless-stopped
    healthcheck:
      test: "curl -f -u elastic:my-password http://localhost:9200/_cluster/health"
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - 9200:9200
    environment:
      ELASTIC_PASSWORD: "my-password"
      "discovery.type": single-node
      "xpack.security.http.ssl.enabled": false

  kibana-users:
    image: curlimages/curl
    depends_on:
      elasticsearch:
        condition: service_healthy
    command:
      - /opt/scripts/create_kibana_users.sh
    volumes:
      - ./kibana:/opt/scripts
    environment:
      ELASTICSEARCH_HOST: "http://elasticsearch:9200"
      ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: "my-password"
      KIBANA_USER: "kibana-user"
      KIBANA_PASSWORD: "kibana-password"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    restart: unless-stopped
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana-users:
        condition: service_completed_successfully
    healthcheck:
      test: "curl -f http://localhost:5601/status"
      start_period: 5s
      interval: 10s
      timeout: 5s
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      ELASTICSEARCH_USERNAME: "kibana-user"
      ELASTICSEARCH_PASSWORD: "kibana-password"